/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppWorkersRouteImport } from './routes/app.workers'
import { Route as AppWorkLogsRouteImport } from './routes/app.work-logs'
import { Route as AppWipRouteImport } from './routes/app.wip'
import { Route as AppWarehousesRouteImport } from './routes/app.warehouses'
import { Route as AppVehiclesRouteImport } from './routes/app.vehicles'
import { Route as AppUtilitiesRouteImport } from './routes/app.utilities'
import { Route as AppUsersRouteImport } from './routes/app.users'
import { Route as AppSuppliersRouteImport } from './routes/app.suppliers'
import { Route as AppStationsRouteImport } from './routes/app.stations'
import { Route as AppStagesRouteImport } from './routes/app.stages'
import { Route as AppRequestsRouteImport } from './routes/app.requests'
import { Route as AppRateCardRouteImport } from './routes/app.rate-card'
import { Route as AppQuickOrderRouteImport } from './routes/app.quick-order'
import { Route as AppPurchaseOrdersRouteImport } from './routes/app.purchase-orders'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppProductsRouteImport } from './routes/app.products'
import { Route as AppPeopleRouteImport } from './routes/app.people'
import { Route as AppMovementsRouteImport } from './routes/app.movements'
import { Route as AppMouldsRouteImport } from './routes/app.moulds'
import { Route as AppManufacturingRouteImport } from './routes/app.manufacturing'
import { Route as AppMachinesRouteImport } from './routes/app.machines'
import { Route as AppInventoryRouteImport } from './routes/app.inventory'
import { Route as AppHelpRouteImport } from './routes/app.help'
import { Route as AppGoodsReturnsRouteImport } from './routes/app.goods-returns'
import { Route as AppDispatchOrdersRouteImport } from './routes/app.dispatch-orders'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppCustomersRouteImport } from './routes/app.customers'
import { Route as AppCommandCenterRouteImport } from './routes/app.command-center'
import { Route as AppCategoriesRouteImport } from './routes/app.categories'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as AppAiInsightsRouteImport } from './routes/app.ai-insights'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as AppAboutRouteImport } from './routes/app.about'
import { Route as AppWorkersAttendanceRouteImport } from './routes/app.workers.attendance'
import { Route as AppWorkersIdRouteImport } from './routes/app.workers.$id'
import { Route as AppStaffingDailyRouteImport } from './routes/app.staffing.daily'
import { Route as AppSettingsUsersRouteImport } from './routes/app.settings.users'
import { Route as AppManufacturingMoIdRouteImport } from './routes/app.manufacturing.$moId'
import { Route as AppMachinesIdRouteImport } from './routes/app.machines.$id'
import { Route as AppAdminSystemRouteImport } from './routes/app.admin.system'
import { Route as AppAdminStaffingRouteImport } from './routes/app.admin.staffing'
import { Route as AppAdminPresetsRouteImport } from './routes/app.admin.presets'
import { Route as AppAdminInventorySettingsRouteImport } from './routes/app.admin.inventory-settings'
import { Route as AppAdminAuditRouteImport } from './routes/app.admin.audit'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkersRoute = AppWorkersRouteImport.update({
  id: '/workers',
  path: '/workers',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkLogsRoute = AppWorkLogsRouteImport.update({
  id: '/work-logs',
  path: '/work-logs',
  getParentRoute: () => AppRoute,
} as any)
const AppWipRoute = AppWipRouteImport.update({
  id: '/wip',
  path: '/wip',
  getParentRoute: () => AppRoute,
} as any)
const AppWarehousesRoute = AppWarehousesRouteImport.update({
  id: '/warehouses',
  path: '/warehouses',
  getParentRoute: () => AppRoute,
} as any)
const AppVehiclesRoute = AppVehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => AppRoute,
} as any)
const AppUtilitiesRoute = AppUtilitiesRouteImport.update({
  id: '/utilities',
  path: '/utilities',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppSuppliersRoute = AppSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AppRoute,
} as any)
const AppStationsRoute = AppStationsRouteImport.update({
  id: '/stations',
  path: '/stations',
  getParentRoute: () => AppRoute,
} as any)
const AppStagesRoute = AppStagesRouteImport.update({
  id: '/stages',
  path: '/stages',
  getParentRoute: () => AppRoute,
} as any)
const AppRequestsRoute = AppRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AppRoute,
} as any)
const AppRateCardRoute = AppRateCardRouteImport.update({
  id: '/rate-card',
  path: '/rate-card',
  getParentRoute: () => AppRoute,
} as any)
const AppQuickOrderRoute = AppQuickOrderRouteImport.update({
  id: '/quick-order',
  path: '/quick-order',
  getParentRoute: () => AppRoute,
} as any)
const AppPurchaseOrdersRoute = AppPurchaseOrdersRouteImport.update({
  id: '/purchase-orders',
  path: '/purchase-orders',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsRoute = AppProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppRoute,
} as any)
const AppPeopleRoute = AppPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => AppRoute,
} as any)
const AppMovementsRoute = AppMovementsRouteImport.update({
  id: '/movements',
  path: '/movements',
  getParentRoute: () => AppRoute,
} as any)
const AppMouldsRoute = AppMouldsRouteImport.update({
  id: '/moulds',
  path: '/moulds',
  getParentRoute: () => AppRoute,
} as any)
const AppManufacturingRoute = AppManufacturingRouteImport.update({
  id: '/manufacturing',
  path: '/manufacturing',
  getParentRoute: () => AppRoute,
} as any)
const AppMachinesRoute = AppMachinesRouteImport.update({
  id: '/machines',
  path: '/machines',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppHelpRoute = AppHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AppRoute,
} as any)
const AppGoodsReturnsRoute = AppGoodsReturnsRouteImport.update({
  id: '/goods-returns',
  path: '/goods-returns',
  getParentRoute: () => AppRoute,
} as any)
const AppDispatchOrdersRoute = AppDispatchOrdersRouteImport.update({
  id: '/dispatch-orders',
  path: '/dispatch-orders',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppCommandCenterRoute = AppCommandCenterRouteImport.update({
  id: '/command-center',
  path: '/command-center',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoriesRoute = AppCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAiInsightsRoute = AppAiInsightsRouteImport.update({
  id: '/ai-insights',
  path: '/ai-insights',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppAboutRoute = AppAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkersAttendanceRoute = AppWorkersAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppWorkersRoute,
} as any)
const AppWorkersIdRoute = AppWorkersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppWorkersRoute,
} as any)
const AppStaffingDailyRoute = AppStaffingDailyRouteImport.update({
  id: '/staffing/daily',
  path: '/staffing/daily',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsUsersRoute = AppSettingsUsersRouteImport.update({
  id: '/settings/users',
  path: '/settings/users',
  getParentRoute: () => AppRoute,
} as any)
const AppManufacturingMoIdRoute = AppManufacturingMoIdRouteImport.update({
  id: '/$moId',
  path: '/$moId',
  getParentRoute: () => AppManufacturingRoute,
} as any)
const AppMachinesIdRoute = AppMachinesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppMachinesRoute,
} as any)
const AppAdminSystemRoute = AppAdminSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminStaffingRoute = AppAdminStaffingRouteImport.update({
  id: '/staffing',
  path: '/staffing',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminPresetsRoute = AppAdminPresetsRouteImport.update({
  id: '/presets',
  path: '/presets',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminInventorySettingsRoute =
  AppAdminInventorySettingsRouteImport.update({
    id: '/inventory-settings',
    path: '/inventory-settings',
    getParentRoute: () => AppAdminRoute,
  } as any)
const AppAdminAuditRoute = AppAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/about': typeof AppAboutRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/ai-insights': typeof AppAiInsightsRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/categories': typeof AppCategoriesRoute
  '/app/command-center': typeof AppCommandCenterRoute
  '/app/customers': typeof AppCustomersRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/dispatch-orders': typeof AppDispatchOrdersRoute
  '/app/goods-returns': typeof AppGoodsReturnsRoute
  '/app/help': typeof AppHelpRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/machines': typeof AppMachinesRouteWithChildren
  '/app/manufacturing': typeof AppManufacturingRouteWithChildren
  '/app/moulds': typeof AppMouldsRoute
  '/app/movements': typeof AppMovementsRoute
  '/app/people': typeof AppPeopleRoute
  '/app/products': typeof AppProductsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/purchase-orders': typeof AppPurchaseOrdersRoute
  '/app/quick-order': typeof AppQuickOrderRoute
  '/app/rate-card': typeof AppRateCardRoute
  '/app/requests': typeof AppRequestsRoute
  '/app/stages': typeof AppStagesRoute
  '/app/stations': typeof AppStationsRoute
  '/app/suppliers': typeof AppSuppliersRoute
  '/app/users': typeof AppUsersRoute
  '/app/utilities': typeof AppUtilitiesRoute
  '/app/vehicles': typeof AppVehiclesRoute
  '/app/warehouses': typeof AppWarehousesRoute
  '/app/wip': typeof AppWipRoute
  '/app/work-logs': typeof AppWorkLogsRoute
  '/app/workers': typeof AppWorkersRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/admin/audit': typeof AppAdminAuditRoute
  '/app/admin/inventory-settings': typeof AppAdminInventorySettingsRoute
  '/app/admin/presets': typeof AppAdminPresetsRoute
  '/app/admin/staffing': typeof AppAdminStaffingRoute
  '/app/admin/system': typeof AppAdminSystemRoute
  '/app/machines/$id': typeof AppMachinesIdRoute
  '/app/manufacturing/$moId': typeof AppManufacturingMoIdRoute
  '/app/settings/users': typeof AppSettingsUsersRoute
  '/app/staffing/daily': typeof AppStaffingDailyRoute
  '/app/workers/$id': typeof AppWorkersIdRoute
  '/app/workers/attendance': typeof AppWorkersAttendanceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/about': typeof AppAboutRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/ai-insights': typeof AppAiInsightsRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/categories': typeof AppCategoriesRoute
  '/app/command-center': typeof AppCommandCenterRoute
  '/app/customers': typeof AppCustomersRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/dispatch-orders': typeof AppDispatchOrdersRoute
  '/app/goods-returns': typeof AppGoodsReturnsRoute
  '/app/help': typeof AppHelpRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/machines': typeof AppMachinesRouteWithChildren
  '/app/manufacturing': typeof AppManufacturingRouteWithChildren
  '/app/moulds': typeof AppMouldsRoute
  '/app/movements': typeof AppMovementsRoute
  '/app/people': typeof AppPeopleRoute
  '/app/products': typeof AppProductsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/purchase-orders': typeof AppPurchaseOrdersRoute
  '/app/quick-order': typeof AppQuickOrderRoute
  '/app/rate-card': typeof AppRateCardRoute
  '/app/requests': typeof AppRequestsRoute
  '/app/stages': typeof AppStagesRoute
  '/app/stations': typeof AppStationsRoute
  '/app/suppliers': typeof AppSuppliersRoute
  '/app/users': typeof AppUsersRoute
  '/app/utilities': typeof AppUtilitiesRoute
  '/app/vehicles': typeof AppVehiclesRoute
  '/app/warehouses': typeof AppWarehousesRoute
  '/app/wip': typeof AppWipRoute
  '/app/work-logs': typeof AppWorkLogsRoute
  '/app/workers': typeof AppWorkersRouteWithChildren
  '/app': typeof AppIndexRoute
  '/app/admin/audit': typeof AppAdminAuditRoute
  '/app/admin/inventory-settings': typeof AppAdminInventorySettingsRoute
  '/app/admin/presets': typeof AppAdminPresetsRoute
  '/app/admin/staffing': typeof AppAdminStaffingRoute
  '/app/admin/system': typeof AppAdminSystemRoute
  '/app/machines/$id': typeof AppMachinesIdRoute
  '/app/manufacturing/$moId': typeof AppManufacturingMoIdRoute
  '/app/settings/users': typeof AppSettingsUsersRoute
  '/app/staffing/daily': typeof AppStaffingDailyRoute
  '/app/workers/$id': typeof AppWorkersIdRoute
  '/app/workers/attendance': typeof AppWorkersAttendanceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/about': typeof AppAboutRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/ai-insights': typeof AppAiInsightsRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/categories': typeof AppCategoriesRoute
  '/app/command-center': typeof AppCommandCenterRoute
  '/app/customers': typeof AppCustomersRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/dispatch-orders': typeof AppDispatchOrdersRoute
  '/app/goods-returns': typeof AppGoodsReturnsRoute
  '/app/help': typeof AppHelpRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/machines': typeof AppMachinesRouteWithChildren
  '/app/manufacturing': typeof AppManufacturingRouteWithChildren
  '/app/moulds': typeof AppMouldsRoute
  '/app/movements': typeof AppMovementsRoute
  '/app/people': typeof AppPeopleRoute
  '/app/products': typeof AppProductsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/purchase-orders': typeof AppPurchaseOrdersRoute
  '/app/quick-order': typeof AppQuickOrderRoute
  '/app/rate-card': typeof AppRateCardRoute
  '/app/requests': typeof AppRequestsRoute
  '/app/stages': typeof AppStagesRoute
  '/app/stations': typeof AppStationsRoute
  '/app/suppliers': typeof AppSuppliersRoute
  '/app/users': typeof AppUsersRoute
  '/app/utilities': typeof AppUtilitiesRoute
  '/app/vehicles': typeof AppVehiclesRoute
  '/app/warehouses': typeof AppWarehousesRoute
  '/app/wip': typeof AppWipRoute
  '/app/work-logs': typeof AppWorkLogsRoute
  '/app/workers': typeof AppWorkersRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/admin/audit': typeof AppAdminAuditRoute
  '/app/admin/inventory-settings': typeof AppAdminInventorySettingsRoute
  '/app/admin/presets': typeof AppAdminPresetsRoute
  '/app/admin/staffing': typeof AppAdminStaffingRoute
  '/app/admin/system': typeof AppAdminSystemRoute
  '/app/machines/$id': typeof AppMachinesIdRoute
  '/app/manufacturing/$moId': typeof AppManufacturingMoIdRoute
  '/app/settings/users': typeof AppSettingsUsersRoute
  '/app/staffing/daily': typeof AppStaffingDailyRoute
  '/app/workers/$id': typeof AppWorkersIdRoute
  '/app/workers/attendance': typeof AppWorkersAttendanceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/app/about'
    | '/app/admin'
    | '/app/ai-insights'
    | '/app/analytics'
    | '/app/categories'
    | '/app/command-center'
    | '/app/customers'
    | '/app/dashboard'
    | '/app/dispatch-orders'
    | '/app/goods-returns'
    | '/app/help'
    | '/app/inventory'
    | '/app/machines'
    | '/app/manufacturing'
    | '/app/moulds'
    | '/app/movements'
    | '/app/people'
    | '/app/products'
    | '/app/profile'
    | '/app/purchase-orders'
    | '/app/quick-order'
    | '/app/rate-card'
    | '/app/requests'
    | '/app/stages'
    | '/app/stations'
    | '/app/suppliers'
    | '/app/users'
    | '/app/utilities'
    | '/app/vehicles'
    | '/app/warehouses'
    | '/app/wip'
    | '/app/work-logs'
    | '/app/workers'
    | '/app/'
    | '/app/admin/audit'
    | '/app/admin/inventory-settings'
    | '/app/admin/presets'
    | '/app/admin/staffing'
    | '/app/admin/system'
    | '/app/machines/$id'
    | '/app/manufacturing/$moId'
    | '/app/settings/users'
    | '/app/staffing/daily'
    | '/app/workers/$id'
    | '/app/workers/attendance'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app/about'
    | '/app/admin'
    | '/app/ai-insights'
    | '/app/analytics'
    | '/app/categories'
    | '/app/command-center'
    | '/app/customers'
    | '/app/dashboard'
    | '/app/dispatch-orders'
    | '/app/goods-returns'
    | '/app/help'
    | '/app/inventory'
    | '/app/machines'
    | '/app/manufacturing'
    | '/app/moulds'
    | '/app/movements'
    | '/app/people'
    | '/app/products'
    | '/app/profile'
    | '/app/purchase-orders'
    | '/app/quick-order'
    | '/app/rate-card'
    | '/app/requests'
    | '/app/stages'
    | '/app/stations'
    | '/app/suppliers'
    | '/app/users'
    | '/app/utilities'
    | '/app/vehicles'
    | '/app/warehouses'
    | '/app/wip'
    | '/app/work-logs'
    | '/app/workers'
    | '/app'
    | '/app/admin/audit'
    | '/app/admin/inventory-settings'
    | '/app/admin/presets'
    | '/app/admin/staffing'
    | '/app/admin/system'
    | '/app/machines/$id'
    | '/app/manufacturing/$moId'
    | '/app/settings/users'
    | '/app/staffing/daily'
    | '/app/workers/$id'
    | '/app/workers/attendance'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/app/about'
    | '/app/admin'
    | '/app/ai-insights'
    | '/app/analytics'
    | '/app/categories'
    | '/app/command-center'
    | '/app/customers'
    | '/app/dashboard'
    | '/app/dispatch-orders'
    | '/app/goods-returns'
    | '/app/help'
    | '/app/inventory'
    | '/app/machines'
    | '/app/manufacturing'
    | '/app/moulds'
    | '/app/movements'
    | '/app/people'
    | '/app/products'
    | '/app/profile'
    | '/app/purchase-orders'
    | '/app/quick-order'
    | '/app/rate-card'
    | '/app/requests'
    | '/app/stages'
    | '/app/stations'
    | '/app/suppliers'
    | '/app/users'
    | '/app/utilities'
    | '/app/vehicles'
    | '/app/warehouses'
    | '/app/wip'
    | '/app/work-logs'
    | '/app/workers'
    | '/app/'
    | '/app/admin/audit'
    | '/app/admin/inventory-settings'
    | '/app/admin/presets'
    | '/app/admin/staffing'
    | '/app/admin/system'
    | '/app/machines/$id'
    | '/app/manufacturing/$moId'
    | '/app/settings/users'
    | '/app/staffing/daily'
    | '/app/workers/$id'
    | '/app/workers/attendance'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/workers': {
      id: '/app/workers'
      path: '/workers'
      fullPath: '/app/workers'
      preLoaderRoute: typeof AppWorkersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/work-logs': {
      id: '/app/work-logs'
      path: '/work-logs'
      fullPath: '/app/work-logs'
      preLoaderRoute: typeof AppWorkLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/wip': {
      id: '/app/wip'
      path: '/wip'
      fullPath: '/app/wip'
      preLoaderRoute: typeof AppWipRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/warehouses': {
      id: '/app/warehouses'
      path: '/warehouses'
      fullPath: '/app/warehouses'
      preLoaderRoute: typeof AppWarehousesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/vehicles': {
      id: '/app/vehicles'
      path: '/vehicles'
      fullPath: '/app/vehicles'
      preLoaderRoute: typeof AppVehiclesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/utilities': {
      id: '/app/utilities'
      path: '/utilities'
      fullPath: '/app/utilities'
      preLoaderRoute: typeof AppUtilitiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/users': {
      id: '/app/users'
      path: '/users'
      fullPath: '/app/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/suppliers': {
      id: '/app/suppliers'
      path: '/suppliers'
      fullPath: '/app/suppliers'
      preLoaderRoute: typeof AppSuppliersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/stations': {
      id: '/app/stations'
      path: '/stations'
      fullPath: '/app/stations'
      preLoaderRoute: typeof AppStationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/stages': {
      id: '/app/stages'
      path: '/stages'
      fullPath: '/app/stages'
      preLoaderRoute: typeof AppStagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/requests': {
      id: '/app/requests'
      path: '/requests'
      fullPath: '/app/requests'
      preLoaderRoute: typeof AppRequestsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/rate-card': {
      id: '/app/rate-card'
      path: '/rate-card'
      fullPath: '/app/rate-card'
      preLoaderRoute: typeof AppRateCardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/quick-order': {
      id: '/app/quick-order'
      path: '/quick-order'
      fullPath: '/app/quick-order'
      preLoaderRoute: typeof AppQuickOrderRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/purchase-orders': {
      id: '/app/purchase-orders'
      path: '/purchase-orders'
      fullPath: '/app/purchase-orders'
      preLoaderRoute: typeof AppPurchaseOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/products': {
      id: '/app/products'
      path: '/products'
      fullPath: '/app/products'
      preLoaderRoute: typeof AppProductsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/people': {
      id: '/app/people'
      path: '/people'
      fullPath: '/app/people'
      preLoaderRoute: typeof AppPeopleRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/movements': {
      id: '/app/movements'
      path: '/movements'
      fullPath: '/app/movements'
      preLoaderRoute: typeof AppMovementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/moulds': {
      id: '/app/moulds'
      path: '/moulds'
      fullPath: '/app/moulds'
      preLoaderRoute: typeof AppMouldsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/manufacturing': {
      id: '/app/manufacturing'
      path: '/manufacturing'
      fullPath: '/app/manufacturing'
      preLoaderRoute: typeof AppManufacturingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/machines': {
      id: '/app/machines'
      path: '/machines'
      fullPath: '/app/machines'
      preLoaderRoute: typeof AppMachinesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inventory': {
      id: '/app/inventory'
      path: '/inventory'
      fullPath: '/app/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/help': {
      id: '/app/help'
      path: '/help'
      fullPath: '/app/help'
      preLoaderRoute: typeof AppHelpRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/goods-returns': {
      id: '/app/goods-returns'
      path: '/goods-returns'
      fullPath: '/app/goods-returns'
      preLoaderRoute: typeof AppGoodsReturnsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dispatch-orders': {
      id: '/app/dispatch-orders'
      path: '/dispatch-orders'
      fullPath: '/app/dispatch-orders'
      preLoaderRoute: typeof AppDispatchOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/customers': {
      id: '/app/customers'
      path: '/customers'
      fullPath: '/app/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/command-center': {
      id: '/app/command-center'
      path: '/command-center'
      fullPath: '/app/command-center'
      preLoaderRoute: typeof AppCommandCenterRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/categories': {
      id: '/app/categories'
      path: '/categories'
      fullPath: '/app/categories'
      preLoaderRoute: typeof AppCategoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ai-insights': {
      id: '/app/ai-insights'
      path: '/ai-insights'
      fullPath: '/app/ai-insights'
      preLoaderRoute: typeof AppAiInsightsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/about': {
      id: '/app/about'
      path: '/about'
      fullPath: '/app/about'
      preLoaderRoute: typeof AppAboutRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/workers/attendance': {
      id: '/app/workers/attendance'
      path: '/attendance'
      fullPath: '/app/workers/attendance'
      preLoaderRoute: typeof AppWorkersAttendanceRouteImport
      parentRoute: typeof AppWorkersRoute
    }
    '/app/workers/$id': {
      id: '/app/workers/$id'
      path: '/$id'
      fullPath: '/app/workers/$id'
      preLoaderRoute: typeof AppWorkersIdRouteImport
      parentRoute: typeof AppWorkersRoute
    }
    '/app/staffing/daily': {
      id: '/app/staffing/daily'
      path: '/staffing/daily'
      fullPath: '/app/staffing/daily'
      preLoaderRoute: typeof AppStaffingDailyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings/users': {
      id: '/app/settings/users'
      path: '/settings/users'
      fullPath: '/app/settings/users'
      preLoaderRoute: typeof AppSettingsUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/manufacturing/$moId': {
      id: '/app/manufacturing/$moId'
      path: '/$moId'
      fullPath: '/app/manufacturing/$moId'
      preLoaderRoute: typeof AppManufacturingMoIdRouteImport
      parentRoute: typeof AppManufacturingRoute
    }
    '/app/machines/$id': {
      id: '/app/machines/$id'
      path: '/$id'
      fullPath: '/app/machines/$id'
      preLoaderRoute: typeof AppMachinesIdRouteImport
      parentRoute: typeof AppMachinesRoute
    }
    '/app/admin/system': {
      id: '/app/admin/system'
      path: '/system'
      fullPath: '/app/admin/system'
      preLoaderRoute: typeof AppAdminSystemRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/staffing': {
      id: '/app/admin/staffing'
      path: '/staffing'
      fullPath: '/app/admin/staffing'
      preLoaderRoute: typeof AppAdminStaffingRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/presets': {
      id: '/app/admin/presets'
      path: '/presets'
      fullPath: '/app/admin/presets'
      preLoaderRoute: typeof AppAdminPresetsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/inventory-settings': {
      id: '/app/admin/inventory-settings'
      path: '/inventory-settings'
      fullPath: '/app/admin/inventory-settings'
      preLoaderRoute: typeof AppAdminInventorySettingsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/audit': {
      id: '/app/admin/audit'
      path: '/audit'
      fullPath: '/app/admin/audit'
      preLoaderRoute: typeof AppAdminAuditRouteImport
      parentRoute: typeof AppAdminRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminAuditRoute: typeof AppAdminAuditRoute
  AppAdminInventorySettingsRoute: typeof AppAdminInventorySettingsRoute
  AppAdminPresetsRoute: typeof AppAdminPresetsRoute
  AppAdminStaffingRoute: typeof AppAdminStaffingRoute
  AppAdminSystemRoute: typeof AppAdminSystemRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminAuditRoute: AppAdminAuditRoute,
  AppAdminInventorySettingsRoute: AppAdminInventorySettingsRoute,
  AppAdminPresetsRoute: AppAdminPresetsRoute,
  AppAdminStaffingRoute: AppAdminStaffingRoute,
  AppAdminSystemRoute: AppAdminSystemRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppMachinesRouteChildren {
  AppMachinesIdRoute: typeof AppMachinesIdRoute
}

const AppMachinesRouteChildren: AppMachinesRouteChildren = {
  AppMachinesIdRoute: AppMachinesIdRoute,
}

const AppMachinesRouteWithChildren = AppMachinesRoute._addFileChildren(
  AppMachinesRouteChildren,
)

interface AppManufacturingRouteChildren {
  AppManufacturingMoIdRoute: typeof AppManufacturingMoIdRoute
}

const AppManufacturingRouteChildren: AppManufacturingRouteChildren = {
  AppManufacturingMoIdRoute: AppManufacturingMoIdRoute,
}

const AppManufacturingRouteWithChildren =
  AppManufacturingRoute._addFileChildren(AppManufacturingRouteChildren)

interface AppWorkersRouteChildren {
  AppWorkersIdRoute: typeof AppWorkersIdRoute
  AppWorkersAttendanceRoute: typeof AppWorkersAttendanceRoute
}

const AppWorkersRouteChildren: AppWorkersRouteChildren = {
  AppWorkersIdRoute: AppWorkersIdRoute,
  AppWorkersAttendanceRoute: AppWorkersAttendanceRoute,
}

const AppWorkersRouteWithChildren = AppWorkersRoute._addFileChildren(
  AppWorkersRouteChildren,
)

interface AppRouteChildren {
  AppAboutRoute: typeof AppAboutRoute
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppAiInsightsRoute: typeof AppAiInsightsRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppCategoriesRoute: typeof AppCategoriesRoute
  AppCommandCenterRoute: typeof AppCommandCenterRoute
  AppCustomersRoute: typeof AppCustomersRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDispatchOrdersRoute: typeof AppDispatchOrdersRoute
  AppGoodsReturnsRoute: typeof AppGoodsReturnsRoute
  AppHelpRoute: typeof AppHelpRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppMachinesRoute: typeof AppMachinesRouteWithChildren
  AppManufacturingRoute: typeof AppManufacturingRouteWithChildren
  AppMouldsRoute: typeof AppMouldsRoute
  AppMovementsRoute: typeof AppMovementsRoute
  AppPeopleRoute: typeof AppPeopleRoute
  AppProductsRoute: typeof AppProductsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppPurchaseOrdersRoute: typeof AppPurchaseOrdersRoute
  AppQuickOrderRoute: typeof AppQuickOrderRoute
  AppRateCardRoute: typeof AppRateCardRoute
  AppRequestsRoute: typeof AppRequestsRoute
  AppStagesRoute: typeof AppStagesRoute
  AppStationsRoute: typeof AppStationsRoute
  AppSuppliersRoute: typeof AppSuppliersRoute
  AppUsersRoute: typeof AppUsersRoute
  AppUtilitiesRoute: typeof AppUtilitiesRoute
  AppVehiclesRoute: typeof AppVehiclesRoute
  AppWarehousesRoute: typeof AppWarehousesRoute
  AppWipRoute: typeof AppWipRoute
  AppWorkLogsRoute: typeof AppWorkLogsRoute
  AppWorkersRoute: typeof AppWorkersRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppSettingsUsersRoute: typeof AppSettingsUsersRoute
  AppStaffingDailyRoute: typeof AppStaffingDailyRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAboutRoute: AppAboutRoute,
  AppAdminRoute: AppAdminRouteWithChildren,
  AppAiInsightsRoute: AppAiInsightsRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppCategoriesRoute: AppCategoriesRoute,
  AppCommandCenterRoute: AppCommandCenterRoute,
  AppCustomersRoute: AppCustomersRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDispatchOrdersRoute: AppDispatchOrdersRoute,
  AppGoodsReturnsRoute: AppGoodsReturnsRoute,
  AppHelpRoute: AppHelpRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppMachinesRoute: AppMachinesRouteWithChildren,
  AppManufacturingRoute: AppManufacturingRouteWithChildren,
  AppMouldsRoute: AppMouldsRoute,
  AppMovementsRoute: AppMovementsRoute,
  AppPeopleRoute: AppPeopleRoute,
  AppProductsRoute: AppProductsRoute,
  AppProfileRoute: AppProfileRoute,
  AppPurchaseOrdersRoute: AppPurchaseOrdersRoute,
  AppQuickOrderRoute: AppQuickOrderRoute,
  AppRateCardRoute: AppRateCardRoute,
  AppRequestsRoute: AppRequestsRoute,
  AppStagesRoute: AppStagesRoute,
  AppStationsRoute: AppStationsRoute,
  AppSuppliersRoute: AppSuppliersRoute,
  AppUsersRoute: AppUsersRoute,
  AppUtilitiesRoute: AppUtilitiesRoute,
  AppVehiclesRoute: AppVehiclesRoute,
  AppWarehousesRoute: AppWarehousesRoute,
  AppWipRoute: AppWipRoute,
  AppWorkLogsRoute: AppWorkLogsRoute,
  AppWorkersRoute: AppWorkersRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppSettingsUsersRoute: AppSettingsUsersRoute,
  AppStaffingDailyRoute: AppStaffingDailyRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
